

[tool.uv]
find-links = [
    "https://storage.googleapis.com/jax-releases/libtpu_releases.html",
]
prerelease = "allow"


[tool.setuptools]
packages = ["BS_RL"] # 只包含主包"cleanrl_utils"


# 定义torch的CPU源
[tool.uv.sources]
torch = [
    { index = "pytorch-cpu" },
]

# 定义CPU索引
[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[project]
name = "BS_RL"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"

dependencies = [
    "flax",
    "optax",
    "stable_baselines3",
    "torch",#SB3依赖，必须显式安装，否则会装GPU版
    # "envpool",
    "wandb<0.19",
    "tyro",
    "numpy<2",
    "pygame",
    "gymnasium[atari,accept-rom-license,other]",
    "joblib",
    "pyinstrument",
    "xprof",
    # "tf-keras",
    # "tensorflow==2.18",
    # "tensorboard==2.18",
    # "tensorboard-plugin-profile==2.18",
    # "cloud-tpu-profiler>=2.3.0",
]
# 可选依赖 - 只需要CPU版本
[project.optional-dependencies]
cpu = [
    "torch>=2.0.0",
    # 如果需要其他torch相关包，也在这里添加
    # "torchvision",
    # "torchaudio", 
]
tpu = [
    'jax[tpu]==0.5.*', # 保持flax的版本近乎不变(0.10.4 -> 0.10.4)，代码完全不变 SPS 120->140 说明0.4版本的性能更好!
    # 可惜呀，flax.nn.scan用了jax v0.5的api：jax.api_util.debug_info导致报错
    # .venv/lib/python3.11/site-packages/flax/core/axes_scan.py 手动将debug_info去掉即可用jax v0.4，可是发现和jax v0.5的性能差不多，起始SPS都是30，所以还是用v0.5吧
]
gpu = [
    'jax[cuda12]==0.4.26', # 0.4.26对应cuDNN 9(kaggle镜像安装的版本)，系统cuda和jax所使用的cuda需保持一致。不知道jax的cuda版本是多少的看用下面的命令可以看，需注意不能用uv pip，它似乎不能正确检索
    # pip install "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
]
box2d = [
    "gymnasium[box2d]",
]

